#!/bin/sh
#
# /etc/rc.d/wlan: start/stop wireless interface
#

case $1 in
	start)
		/usr/sbin/wpa_supplicant -i wlp2s0 -c /etc/wpa_supplicant.conf -B -D nl80211
		;;
	stop)
		/usr/bin/killall -q /usr/sbin/wpa_supplicant
		;;
	restart)
		$0 stop
		$0 start
		;;
	*)
		echo "Usage: $0 [start|stop|restart]"
		;;
esac
